<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFlpuxsj\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFlpuxsj/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerFlpuxsj.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerFlpuxsj\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerFlpuxsj\appProdProjectContainer([
    'container.build_hash' => 'Flpuxsj',
    'container.build_id' => 'acab41b1',
    'container.build_time' => 1689851849,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFlpuxsj');
