<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5tiymx7\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5tiymx7/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container5tiymx7.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container5tiymx7\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container5tiymx7\appDevDebugProjectContainer([
    'container.build_hash' => '5tiymx7',
    'container.build_id' => '730a4dd8',
    'container.build_time' => 1689817667,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5tiymx7');
